### ISSUE TITLE
Eliminate exceeding caching (was: Language changes temperature)

### ISSUE THREAD

**Issue by radio-rogal** [chubin/wttr.in#288]
Looks strange: when I add non-English language it changes current temperature.

```
[ur6lad@host 10:54 AM ~]$ curl wttr.in/Kharkiv?0
Weather report: Kharkiv

     \   /     Sunny
      .-.      1..4 °C        
   ― (   ) ―   ↘ 15 km/h      
      `-’      10 km          
     /   \     0.0 mm         
[ur6lad@host 10:54 AM ~]$ curl -H "Accept-Language: uk" wttr.in/Kharkiv?0
Прогноз погоди для: Kharkiv

    \  /       Змінна хмарність
  _ /"".-.     2..5 °C        
    \_(   ).   ↓ 11 km/h      
    /(___(__)  10 km          
               0.0 mm         
[ur6lad@host 10:55 AM ~]$ curl -H "Accept-Language: ru" wttr.in/Kharkiv?0
Прогноз погоды: Kharkiv

    \  /       Переменная облачность
  _ /"".-.     2..5 °C        
    \_(   ).   ↓ 11 km/h      
    /(___(__)  10 km          
               0.0 mm         
[ur6lad@host 10:55 AM ~]$ curl -H "Accept-Language: en" wttr.in/Kharkiv?0
Weather report: Kharkiv

     \   /     Sunny
      .-.      1..4 °C        
   ― (   ) ―   ↘ 15 km/h      
      `-’      10 km          
     /   \     0.0 mm     
```

As you can see for Russian and Ukrainian weather is warmer than English.

**Comment by chubin** [comment]
Yes, it is known, that is a caching artifact. It is possible that some response (the English one in this case) was saved in the cache (because someone asked for the same just a couple of minutes before), and so the answer is being delivered basing on the cache. If you use some other language for the query (that was not in the recent time) (Russian or Ukrainian in this case) the answered can't be found in the cache, and it is recalculated. In this case it is possible that it will differ from the cached one (the good news is that such answers more accurate).

And still some caching paths can be eliminated/reoptimized, so this issue is perfectly legitimate.
