### ISSUE TITLE
?m metric switch not working

### ISSUE THREAD

**Issue by willqak** [chubin/wttr.in#300]
The ?m switch can not be used when ? is used for anything else. The first example below returns Imperial and the second returns SI. You can not mix the two switches.
A solution is needed to enable SI regardless of other ? options. 
Since SI is the official measurement system ( in the US also), SI should be default and force users to use the ?u switch if Imperial is wanted. 

curl wttr.in/Pittsfield,MA?format=3
curl wttr.in/Pittsfield,MA?m

**Comment by chubin** [comment]
> The ?m switch can not be used when ? is used for anything else

Why? Just combine the options with `&`, as usually (I am in Europe that's why I have metric units by default, and thus I switch to USCS):
```
$ curl wttr.in/Pittsfield,MA?format=3\&u
Pittsfield,MA: ☀️ +68°F
```

Regarding SI/USCS maybe you are right, that SI should be used everywhere by default. Not sure about this. But other US users seem to be happy with the USCS default

**Comment by chubin** [comment]
(please say, if you think we should reopen this issue)
(maybe we should make a poll in twitter regarding this?)

**Comment by willqak** [comment]
Thanks, I'm not a coder and I didn't see an option for the \&m switch. I
was stuck on the ? format.
My global settings all use SI as default. I use SI since I was in the Army
for 24 years and both the US military and all her allies use SI
exclusively. The "C" in USCS is customary, meaning informal, non scientific
measurements. The elderly keep up political pressure to keep the USCS. The
USA had the Metric Act of 1972 that failed to metricify the USA due to old,
close to death geezers that refuse to give up the pound, quart, farthing,
bushel, barrel, (and the Stupid Kraut Fahrenheit with his moronic 32
degree/212 degree for water??? 0-100 Celsius- simple, easy, and it meshes
with the SI units in a complete connected system. USCS is a mess with lots
of arbitrary units that make no sense. Units like 5/32nds or 3/16th or
25/64th inches are a nightmare to quickly add or subtract.Unlike
3mm,4mm,10mm,19mm,etc that are nice and easy with SI.
I say make SI default and make these lazy people do the work to convert if
they wish. Kids are taught in school, but with constant bombardment of USCS
in the media makes it hard for them to use and develop their SI skills.I
say rip the band-aid off and default SI worldwide. They could always use ?u
to compensate for their laziness.
Thanks again for the syntax help.
Will

**Comment by chubin** [comment]
Thank you very much for your detailed comment. It was really interesting for me to read it, because here in Europe the USCS are perceived somehow as strange inadequate units from the XIX century, and that's why it is especially important and useful to have some US-based opinion.

I think that the most controversial unit is F⁰, at least here, the only context where it is being used is "Fahrenheit 451", and no other. Nobody knows what XXX F⁰ means, nobody can read such data. If in the states it is the same with ⁰C, it would be of course not a clever idea to use the Metric units by default.

Is it possible that your point of view is somehow biased, because you are related to the Army, and thus you had a lot of contacts with Europeans, and that' why it is more natural to you to use the metric system/SI?
