### ISSUE TITLE
http://wttr.in/Kyiv_0pq_transparency=200_lang=uk.png

### ISSUE THREAD

**Issue by vitich** [chubin/wttr.in#314]
![Screenshot from 2019-06-13 11-17-50](https://user-images.githubusercontent.com/12166319/59415855-faad0a80-8dcc-11e9-8e20-687143f2b84b.png)

but "lang=en" works...

**Comment by vitich** [comment]
![Screenshot from 2019-06-13 11-21-41](https://user-images.githubusercontent.com/12166319/59416153-81fa7e00-8dcd-11e9-94bf-5dd8018767f5.png)

**Comment by vitich** [comment]
http://wttr.in/Kyiv_0pq_transparency=200_lang=en.png

![Screenshot from 2019-06-13 11-27-20](https://user-images.githubusercontent.com/12166319/59416571-490ed900-8dce-11e9-8c66-53d29b15fbe4.png)

**Comment by vitich** [comment]
Thank you, it works
![Screenshot from 2019-06-13 12-23-55](https://user-images.githubusercontent.com/12166319/59420860-50d27b80-8dd6-11e9-9e8f-44d2e719ba6c.png)

**Comment by vitich** [comment]
It worked, now it's broken again - English instead of Ukrainian

![Screenshot from 2019-06-13 16-09-15](https://user-images.githubusercontent.com/12166319/59435213-c437b580-8df5-11e9-86bc-bbb082ebf86c.png)

**Comment by chubin** [comment]
@vitich Thank you very much for reporting it. We were experiencing some problems because of the high load several days ago, and I suppose the errors you've reported were caused by them. I've checked, if the link you've provided, is working like it is supposed to work.

![Kyiv_0pq_transparency=200_lang=uk](https://user-images.githubusercontent.com/3875145/59861618-7c7ad600-9381-11e9-8e34-9b719b6d35af.png)

(by the way, you can use Київ for the location name too, and the report will be entirely in Ukrainian, without translation)

**Comment by chubin** [comment]
It seems to work.
