### ISSUE TITLE
What geolocator service is used?

### ISSUE THREAD

**Issue by MasterEric** [chubin/wttr.in#331]
I have experienced several issues attempting to develop a pull request for wttr.in on my local machine (adding JSON output).

Among issues with `wego` being different from whatever version is used here, and `weather_data.py` calling WWO instead of `wego`, I have been unable to get landmark parsing (`~Eiffel+Tower`) working.

It appears that `location.py/geolocator()` (https://github.com/chubin/wttr.in/blob/master/lib/location.py#L63) is utilizing an external service, located at localhost:8004. However, this is not described in the setup documentation anywhere.

**Comment by chubin** [comment]
@MasterEric Yes, you are right, our wego ersion diverged from the mainstream several years ago. We are currently working on the next wttr.in version where no external processes called via `subprocess` will be used. Regarding JSON, I don't know what exactly you are implementing, it would be interesting to discuss, but keep in mind that JSON output is already supported, the only thing that is to be implemented yet is http header handling to bypass queries from wttr server to the proxy server. We don't do it, again, because of the new wttr.in version we are working on.
If you need the diverged wego version and the geolocator code, I can email it to you.

**Comment by MasterEric** [comment]
I don't particularly need the geolocator code, I was just wondering why it wasn't included in the project.

According to https://github.com/chubin/wttr.in#supported-output-formats and http://wttr.in/:help, I see no syntax for, or reference to, JSON output. Are you referring to this upcoming new server?

My hope was that it would not be too difficult to create a call that simply outputs the JSON that wego provides: https://github.com/schachmat/wego/blob/master/backends/json.go

**Comment by chubin** [comment]
@MasterEric What I mean, the proxy server (https://github.com/chubin/wttr.in/blob/master/bin/proxy.py) returns the data in JSON anyway; the data is not visible from outside currently, but it would be pretty easy to fix srv.py in such way, that if the query has correspondent header (`Accept: application/json`), the data will be just passed through it

**Comment by MasterEric** [comment]
I was thinking a separate route, such as `https://wttr.in/Detroit.json` or `https://wttr.in/Detroit?format=json`, would be preferable, as currently all other input options are available through modification of the URL.

**Comment by chubin** [comment]
@MasterEric It is a good idea. Probably we should support both of them. Please check out this: `https://wttr.in/Detroit?format=j1` (json format can be changed, and will be changed probably; that's why I used `j1` for the format identifier) (Please also keep in mind that this feature is experimental)

**Comment by MasterEric** [comment]
This is incredibly useful! I'm sure I, along with many other users, would love to have JSON available for scripts and other applications that want to format the data wttr.in provides themselves.

One point to note: `weatherCode` is one of an enumeration of values described here: https://www.worldweatheronline.com/developer/api/docs/weather-icons.aspx and here: https://github.com/chubin/wttr.in/blob/a1517df21f95d86b569e96e2309e3103ef950ed3/lib/constants.py. That should be prominently stated within the documentation for the JSON feature.

I see no other issues, keep up the good work!

**Comment by MasterEric** [comment]
Is this new commit live? What is the URL to access this? I assume the j1 format code is temporary

**Comment by chubin** [comment]
It is live; `j1` format code will stay; if we add new JSON formats, they will be available at `jN` format codes (where N > 1)
