### ISSUE TITLE
out of queries

### ISSUE THREAD

**Issue by lxle** [chubin/wttr.in#348]
seems the weather service is down again due to query limits... any hope of it working again soon?

**Comment by tallguyjenks** [comment]
the website says: 

>Sorry, we processed more than 1M requests today and we ran out of our datasource capacity.
>We hope to solve the problem as soon as possible, so you can enjoy
>your favourite weather service 24x365 even if it rains or snows.

>We will solve the problem as soon as possible.

**Comment by chubin** [comment]
@lxle @tallguyjenks We have actually two problems now (though the second one was caused by the first one):

* the datasource had (and probably still has) an outage, because of which many queries (almost all queries except ones related to Europe) could not be processed.
* wttr.in still tried to process them and because of that went beyond its daily capacity.

What was done:

we fixed the wttr.in behavior in such cases, so it does not retry to process the queries (by default for 1 hour for the region for which the failure happened), and so does not exhaust its capacity.

The capacity will be automatically renews in 2 hours, after that the service will be available again (the second problem will be solved), but it is theoretically possible that because of the datasource issues (if they are still not fixed) some region will have problems for some time (hopefully they wont).

The only possible solution for such outages is to have several uplink datasorces, and reroute queries as needed. It is planned

**Comment by lxle** [comment]
Ok thanks, I'm readying the release of the next version of the LXLE desktop in which wttr.in in used as the default weather app and just wanted to make sure everything would be fine shortly as I didn't want to have to remove it.

**Comment by chubin** [comment]
@lxle It works now

**Comment by chubin** [comment]
@lxle Have you tested the new view (v2.wttr.in) in lxle by the way? Does it work well? Or are some fonts missing?

**Comment by lxle** [comment]
wasn't aware there was a v2.wttr.in

**Comment by chubin** [comment]
@lxle Could you please take a look at it (in the terminal) and check if everything works as expected?
It is experimental, and we try to get as much feedback as possible, and fix as many problems as possible

Just try: `curl v2.wttr.in`

**Comment by lxle** [comment]
looks good for me using sakura

**Comment by chubin** [comment]
@lxle Thank you!

**Comment by dikiaap** [comment]
Ping @chubin. The wttr.in is out of queries again. https://web.archive.org/web/20200108051535/https://wttr.in/

**Comment by chubin** [comment]
@dikiaap Please test
