### ISSUE TITLE
Scalability problem: "500 Internal Server Error" under high load

### ISSUE THREAD

**Issue by prep-gh** [chubin/wttr.in#426]
Question: I saw these at (around) 12pm EST on March 31 2019 on wttr.in.

**500 Internal Server Error**
______________

      nginx/1.10.3

I am seeing 500 errors on my own Flask-based Python WSGI Apache site,
with nothing really shown in the logs to help to diagnose it.

I'd like to help you, 
as it may help me as well.

How often are you getting these 500 errors and 
what steps (if any) are you taking to recover from them?

I sometimes need to reload the site,
and (***worse***) sometimes it corrects itself.

**Comment by chubin** [comment]
It depends on the situation; it is possible, that you and wttr.in have difference reasons for the internal errors. You can dump exceptions backtracks into a logfile and you fill find out qhy they happening.

wttr.in has errors because of the too high load it has, and the server, as it implemented currently, can't handle it sometimes properly. It should be rewritten to handle such high load

**Comment by chubin** [comment]
The problem is fixed. Please write, if you any need any details/help
