### ISSUE TITLE
Options not working

### ISSUE THREAD

**Issue by shinokada** [chubin/wttr.in#427]
According to ` curl wttr.in/:help`:

```
Options can be combined:

    /Paris?0pq
    /Paris?0pq&lang=fr
    /Paris_0pq.png          # in PNG the file mode are specified after _
    /Rome_0pq_lang=it.png   # long options are separated with underscore

```

When I run it, it returns no matches found.

<img width="490" alt="Screen Shot 2020-04-05 at 20 53 31" src="https://user-images.githubusercontent.com/147320/78477082-91ddb700-777f-11ea-9150-4ce2638e9b65.png">

**Comment by ilGallo** [comment]
I had the same problem, solved using `\` before the symbols.
Like this:
`/Paris\?0pq
`
`
  /Paris\?0pq\&lang=fr
`

**Comment by shinokada** [comment]
Thanks @ilGallo. It works.
But I hope @chubin is going to fix this. Because it is not how [URL query works](https://www.wikiwand.com/en/Query_string).

**Comment by chubin** [comment]
The problem here is not the service (or that it handles URL wrongly), but zsh.
zsh tries to process the glob (it thinks that it is a glob because of the `?` in the name),
and it can't find any file matching this glob (`wttr.in/Paris?n`).
If you run `setopt +o nomatch` first, it will work without any escaping

**Comment by shinokada** [comment]
@chubin 
Thanks, it works.
