### ISSUE TITLE
Get sunset and sunrise time

### ISSUE THREAD

**Issue by patri9ck** [chubin/wttr.in#477]
Show the sunset and sunrise time and make it possible to use something like this to retrieve it directly:

Sunset: wttr.in/?format=5
Sunrise: wttr.in/?format=6

**Comment by iago-lito** [comment]
FWIW, they do show up in v2. Not sure about retrieving them directly though.
![Capture d’écran de 2020-06-24 17-18-05](https://user-images.githubusercontent.com/10091387/85583640-b8a0e080-b63e-11ea-9d29-376944fb8d7d.png)

**Comment by chubin** [comment]
Not only in v2!

```
$ curl wttr.in/Montplellier?format=%D+%S+%z+%s+%d
05:06:39 05:41:03 13:14:34 20:48:19 21:22:41
```

and it is even documented:

https://github.com/chubin/wttr.in#one-line-output

(@iago-lito It is unbelievable! We are just a couple of days past 22 June, and the days are several hours shorter now)

**Comment by iago-lito** [comment]
(@chubin I think this phenomenal difference it is mostly due to the fact that `Montpellier` and `Montplellier` point to rather different locations :P)

<sub><sup>(btw this is outrageous, you shouldn't get such a different result when you only happen to mistake on just 1 letter.. you have to report that to the world geography repo)</sup></sub>

**Comment by patri9ck** [comment]
Thanks!

**Comment by chubin** [comment]
@iago-lito I think it is a bug, and it should show the "unknown-location" page here (Oymyakon)
