### ISSUE TITLE
Update screenshot on documentation with English values

### ISSUE THREAD

**Issue by argestes** [chubin/wttr.in#483]
Right now documentation has a Turkish worded screenshot.
You can use this instead.
https://i.imgur.com/metfD6d.png

**Comment by chubin** [comment]
:)

No, you didn't get the wttr.in magic :)
It shows you weather report in your language (I assume Turkish is configured as the main language in your browser).

Actually it should even show the weather for your location,
but your IP adress is hidden by CDN. But language is not hidden

**Comment by volkanto** [comment]
@argestes which documentation/screenshot contains Turkish words? I couldn't see any in the documentation.

**Comment by argestes** [comment]
I'm talking about the screenshot on the Readme. If that's magic it's Firefox's magic ;)

**Comment by argestes** [comment]
We can close this. Readme was updated or some black magic is happening.

**Comment by volkanto** [comment]
I've checked README file multiple times yesterday but couldn't find any screenshot which contains Turkish. As it contains Russian and German samples but definitely not Turkish one.

**Comment by chubin** [comment]
I can just repeat that what I already wrote.

README was not updated, and as I wrote, PNG is always generated on the fly,
basing on the languages headers inside your query. That's why if your browser
uses Turkish, the PNG will be in Turkish, or if it is in Russian or German, it will be
in Russian or German as in @volkanto 's case.

Just open https://wttr.in/MyLocation.png in your browser (you can use any browser, not only firefox; there is no magic from the browser's side, only from the wttr.in's side),
and you will see that it uses your browser language
