### ISSUE TITLE
BUG: Province name is ignored while doing IP-base geolocation

### ISSUE THREAD

**Issue by vzaliva** [chubin/wttr.in#492]
Please see attached screenshot of wttr and weather.com forecast.
There is no sign or rain here and none is likely at this time of year!

![screenshot_20200628_131559](https://user-images.githubusercontent.com/86581/85957400-fb65ff80-b941-11ea-8283-fa5752bd1c48.png)
![screenshot_20200628_131619](https://user-images.githubusercontent.com/86581/85957402-fdc85980-b941-11ea-8f43-d27c28efbb94.png)

**Comment by chubin** [comment]
wttr.in show the report for 
`Saratoga County, New York, United States of America`,
not Saratoga,CA (by default).

please try `saratoga,ca,us` instead

**Comment by vzaliva** [comment]
I did not specify any location. I assume it geolocated me by IP.

**Comment by mathieu-aubin** [comment]
shit happens i guess, now you know you should specify for your current situation (mobile carrier? ISP with way too broad/many ranges of ips and not using selective attribution?)..

Clearly, it's not your fault but it serves as a reminder that geolocation is only as precise as... well... as precise as `insert something that is not very precise here`.

Per example... my ISP attributes me ip addresses that are, for one great thing, part of a very limited range every time my router/modem reconnects. Great for ssh/firewalling stuff i think. As far as geolocation... well, i'm actually about 500km from where my ips 'discover' or locate me. Not so great for weather precision....

I am an owl with relish (the green type) stuck between the left middle sharpest claws, no spark plugs. Yup.

**Comment by chubin** [comment]
I think that it is a bug indeed, because the IP-based geolocation correctly detected location of the IP address,
as `Saratoga, United States`, but it dropped the province, and so it became Saratoga of New York.
It is a bug

**Comment by elliotrushton** [comment]
I'll just add another data point to this in case it's helpful (I'm 99% sure this is the same bug):

When I do a plain curl to `wttr.in` it correctly geo locates me down to my location:
```
$ curl wttr.in
Weather report: Bowen Island, Canada

     \   /     Sunny
      .-.      30..31 °C
   ― (   ) ―   → 11 km/h
      `-’      16 km
     /   \     0.0 mm
```

However, I noticed that the temperate was way off (I wish it was 30°C). If I specify my location:
`$ curl wttr.in/Bowen+Island` I get a very similar weather report but the Location line at the end tells I think the story: 

``` 
$ curl wttr.in/Bowen+Island
Weather report: Bowen+Island

    \  /       Partly cloudy
  _ /"".-.     29..33 °C
    \_(   ).   ↓ 0 km/h
    /(___(__)  14 km
               0.2 mm
[...snip...]
Location: Bowen Island, Charleston County, South Carolina, 29439, United States of America [32.6776793,-79.9598125]
```

So it looks like the geo-ip look up is correctly getting my location (I am on Bowen Island, in Canada) but when using it to look up the weather it's only using the city name.

**Comment by chubin** [comment]
@elliotrushton Yes, it is the very same bug, and #536 (found now by @vzaliva ) is also another reincarnation of the bug. Some part of information (at least province/state name) is getting lost between IP -> LOCATION and LOCATION -> GPS conversion

**Comment by gregdan3** [comment]
Was about to make a new issue when I spotted this. Same occurs for my IP in `Helena,Alabama`; I get results for `Helena,Montana` unless I explicitly pass the location.

**Comment by gregdan3** [comment]
## Breakdown
https://github.com/chubin/wttr.in/blob/master/lib/location.py#L177

I believe we can see the cause of the problem here, where all of your ip based locating methods exclusively return city and country, without any region information.

I had a look at all three of these, and I can see the fix for at least two of them.

### geoip
[geoip in location.py](https://github.com/chubin/wttr.in/blob/master/lib/location.py#L157) offers a region name under `response.subdivisions.name`, seen [here](https://github.com/maxmind/GeoIP2-python/blob/master/README.rst#sync-web-service-example)

It also offers `reponse.location.latitude` and `response.location.longitude`.

### ipinfo
[ipinfo in location.py](https://github.com/chubin/wttr.in/blob/master/lib/location.py#L143) 

`ipinfo` offers a `region` key seen [here](https://ipinfo.io/developers/responses#full-response) in their docs, which looks to be what we want. 

It also offers a comma separated latlong in its `loc` key, if that would be useful.

### ip2location
[ip2location in location.py](https://github.com/chubin/wttr.in/blob/master/lib/location.py#L117)

This one's the most odd, because I'm not sure what you're doing with the semicolon splits here. I assume you're fetching the minimum amount of data from ip2location, but you're only passing an IP key, and their docs suggest you need to pass something to `addons` to get anymore data. With the demo key, I only get back a country code for doing that, even appending country/region/city addons.
Their docs [here](https://www.ip2location.com/web-service/ip2location) suggest there is a `region_name` returned from their API, but that's the v2 api which it doesn't seem like you're using? Again, not sure what's up.


### Other notes
I think you're performing [this invokation](https://github.com/chubin/wttr.in/blob/master/lib/location.py#L295) [two times](https://github.com/chubin/wttr.in/blob/master/lib/location.py#L308) if the input is an IP address; there's a difference between them if the location is some actual location, but if it's an IP, I think you would perform it twice.

Another thing I noted is that you are using the IP address to fetch hemisphere information instead of the location; everyone sees the same phase at the same time, so you won't pass an incorrect name, but the /moon endpoint would show an incorrect side of the moon being lit for somebody in the northern hemisphere querying the moon phase in the southern hemisphere. Except, reading things over, I think fetching the moon phase on `/moon` makes it impossible to fetch a specific location, so... Fair enough!

**Comment by chubin** [comment]
@gregdan3 Gregory thank you a lot for such a detailed analysis, and for the subsequent pull-request. Actually, `lib/location.py` is the messiest place in the code here, and it has been deserving refactoring for a long time. I think we will do it after we merge your pull-request.

Regarding cache invalidation: we already have more than 300k entries in the cache (I think that the name "cache" is a little bit misleading, it should be better call local database), and I would like to keep it, because it handle quite big part of the incoming queries. Some of the entries are, maybe, outdated, but not so much.

So, what I would suggest:

* when writing, write all components of the ip address resolution into the cache (`";".join(parts)`);
* when reading, take only the three first of them;
* the cache entries that have two parts, consider invalid (I will go through the cache and remove such entries).

The rest is looking fine.

Thank you once again fro the great contribution!

**Comment by chubin** [comment]
Cache file format suggestion:

```
COUNTRY_CODE;COUNTRY;REGION;CITY[;REST]
```

* Cache entry has 4 (or more) `;` separated mandatory entries.
* The first one, can be empty or contain the country code, and ignored in code;
*The second, third, and fourth one are joined with `,` and used for conversion into GPS coordinates.

**Comment by gregdan3** [comment]
> @gregdan3 Gregory thank you a lot for such a detailed analysis, and for the subsequent pull-request. Actually, `lib/location.py` is the messiest place in the code here, and it has been deserving refactoring for a long time. I think we will do it after we merge your pull-request.
> 
> Regarding cache invalidation: we already have more than 300k entries in the cache (I think that the name "cache" is a little bit misleading, it should be better call local database), and I would like to keep it, because it handle quite big part of the incoming queries. Some of the entries are, maybe, outdated, but not so much.
> 
> So, what I would suggest:
> 
>     * when writing, write all components of the ip address resolution into the cache (`";".join(parts)`);
> 
>     * when reading, take only the three first of them;
> 
>     * the cache entries that have two parts, consider invalid (I will go through the cache and remove such entries).
> 
> 
> The rest is looking fine.
> 
> Thank you once again fro the great contribution!



> Cache file format suggestion:
> 
> ```
> COUNTRY_CODE;COUNTRY;REGION;CITY[;REST]
> ```
> 
>     * Cache entry has 4 (or more) `;` separated mandatory entries.
> 
>     * The first one, can be empty or contain the country code, and ignored in code;
>       *The second, third, and fourth one are joined with `,` and used for conversion into GPS coordinates.

Thanks for the advice; I'll make those changes this coming Sunday at the latest, and throw the changes back here.

Can I see some examples of the production cache files as well?

**Comment by chubin** [comment]
Sure:

```
$ cat /wttr.in/cache/ip2l/100.24.119.233 ; echo
US;United States;Virginia;Ashburn;39.04372;-77.48749;20146;Amazon Data Services NoVa;amazon.com
$ cat /wttr.in/cache/ip2l/100.24.125.228; echo
US;United States;Virginia;Ashburn;39.04372;-77.48749;20146;Amazon Data Services NoVa;amazon.com
$ cat /wttr.in/cache/ip2l/100.12.67.210; echo
US;United States;New York;New York City;40.71427;-74.00597;10116;Verizon Communications Inc.;verizon.com
```

**Comment by gregdan3** [comment]
> Sure:
> 
> ```
> $ cat /wttr.in/cache/ip2l/100.24.119.233 ; echo
> US;United States;Virginia;Ashburn;39.04372;-77.48749;20146;Amazon Data Services NoVa;amazon.com
> $ cat /wttr.in/cache/ip2l/100.24.125.228; echo
> US;United States;Virginia;Ashburn;39.04372;-77.48749;20146;Amazon Data Services NoVa;amazon.com
> $ cat /wttr.in/cache/ip2l/100.12.67.210; echo
> US;United States;New York;New York City;40.71427;-74.00597;10116;Verizon Communications Inc.;verizon.com
> ```

Would you prefer I emulate this structure? All of the existing IP locationing methods are able to return latlong (the others give it already, but we have to switch ip2location from WS3 to WS5), so I can also add that onto the cache.

**Comment by chubin** [comment]
Yes, it is a good idea

**Comment by gregdan3** [comment]
My pull request is now updated with the requested changes. It should no longer invalidate the cache, but it will not (and cannot) provide exactly the same data as you've shown; it now caches from all three sources, and since not all three sources provide the content after the latlong, I can't be sure how to source that data except for trying a different iplocation method.
