### ISSUE TITLE
i18n add a new language: Occitan

### ISSUE THREAD

**Issue by Quenty-tolosan** [chubin/wttr.in#494]
I open this issue to add a new language.
What file should I use as a template?

Best regards

## Steps

* [x] `lib/translations.py`
* [x] `share/translations/oc.txt`
* [x] help: `share/translations/help-oc.txt`
* [x] v2 translation
* [x] we-lang translation

**Comment by chubin** [comment]
Hi @Quenty-tolosan!

Thank you for your help

I've added the list of steps that we need to do for the translation.
They are fully independent and can be done in any order.

Just for the repository, translate it, and open PRs as you advance,
after each step, or after all steps done, as you wish.
The former is probably better because we can see and test the results sooner

**Comment by chubin** [comment]
@iago-lito Do you speak Occitan too? If I remember it correctly Montpellier was in the Occitanie region?

Should we just fork Occitane translation from the French one, and then just fix the difference,
or it is not so easy?

**Comment by iago-lito** [comment]
@chubin Unfortunately I do not, although you are right about Montpellier and I'm very happy to read that there is an interest in translating to local languages :)

This said, I doubt it would be useful to fork from the French translation, because I think that very few words will be unchanged. It sounds familiar to the ear of a French speaker, but just enough to understand the context, and I recall that the writing differs much.

**Comment by Quenty-tolosan** [comment]
Hello! No it would take more time to change from the French then using a Translation Memory ;)
I do have it in Occitan and some other software for weather were translated so I would only need to validate and translate the rest :) I'm planning to work on it this week end

**Comment by chubin** [comment]
@Quenty-tolosan I'm afraid that you will find no time for the wttr.in translation, and we lose such a great opportunity to have Occitan support for wttr.in. It is very hard to find someone who can help with it, and that was very bug luck that you created this issue. So I hope that you will not disappear.

If you currently have no time for forks, PRs etc, we can start slowly,
with translation of the most basic words:

```
"Morning",
"Day",
"Evening",
"Night",
"Weather report for:",
"Weather",
```
And the next portion (from the v2 view):

```
"Timezone",
"Now",
"Dawn",
"Sunrise",
"Zenith",
"Sunset",
"Dusk"
```

Though some of them maybe actually are not so easy as I thought: Dawn, dusk, sunrise, sunset...

**Comment by Quenty-tolosan** [comment]
Hello!
I'm back and here is my first PR: https://github.com/chubin/wttr.in/pull/501
And:

"Morning", => Matin
"Day",  => Jorn
"Evening", => Vèspre
"Night",  => Nuèch
"Weather report for:",  => «Previsions metèo per :»
"Weather",  => Metèo

"Timezone",  => Zòna orària
"Now",  => Ara
"Dawn",  => Auròra
"Sunrise", => Alba
"Zenith", => Zenit
"Sunset", => A solelh colc
"Dusk" => Entrelutz


I have to say i don't personally make a clear different between dawn an sunrise, or sunset and dusk xD

**Comment by chubin** [comment]
> I have to say i don't personally make a clear different between dawn an sunrise, or sunset and dusk

Actually, there is substantial difference; it is even possible
that there is dusk, but no sunset (or there is is a sunrise, but no dawn):

```
$ curl -ks v2.wttr.in/Mo-i-Rana?F | tail -5 ; echo
Weather: ⛅️  Partly cloudy, +20°C, 49%, ↓6km/h, 1011hPa
Timezone: Europe/Oslo
  Now:    18:30:47+0200 | Dawn:    --------  | Sunrise: 02:33:20
  Zenith: 13:09:23      | Sunset:  23:41:35  | Dusk:    --------
Location: Mo i Rana, Rana, Nordland, 8622, Norge [66.3166,14.1496]
```

Translation:

It seems to work and it looks pretty cool:

https://oc.wttr.in/Tolosa,%20Occitània
```
curl https://oc.wttr.in/Tolosa,Occitània
```

@iago-lito it is, by the way, a good example of a case that I mentioned in #500 
Ordinary weather services couldn't resolve `Tolosa,Occitània`,
they have no idea what it is, but not wttr.in.

Back to the translation:

help, messages, etc. work also.

v2.wttr.in translation was also added; it does not work yet, but it is a problem
with the v2 view itself, not with the translation.

@Quenty-tolosan, I added your account name (because I have no your real name)
to https://wttr.in/:translation
Please say (or make a PR) if the name must be hidden/changed

**Comment by Quenty-tolosan** [comment]
Brillant! Thinks for having taken the time to fix the resolution of Tolosa :D
It means a lot :D
I will have to shorten some strings.
A question: where do the strings for short name of day come from?

**Comment by chubin** [comment]
Quentin, thank you again!
