### ISSUE TITLE
City *sometimes* not found for formatted query

### ISSUE THREAD

**Issue by aydoo** [chubin/wttr.in#499]
Sometimes (e.g. right when I post this), in the following two commands, the city is found in the first one but not in the second one:

- `curl wttr.in/Aachen?format=%t`
    - Output: `+24°C`
- `curl wttr.in/Aachen?format=%c`
    - Output: `Unknown location; please try ~50.776351,6.083862`

This is difficult to reproduce reliably, because it only happens _sometimes_. If this is a capacity issue, a more expressive response should be given.

**Comment by chubin** [comment]
Yes, it was a temporary issue; agree that the message must be more appropriate

**Comment by alexanderstephan** [comment]
How is this related to a capacity issue exactly? E.g it happens for `curl  'wttr.in/München?format=3'` and for curl 'wttr.in/München?format=3', but not for `curl  'wttr.in/München?format=3'`.  I would presume server limitations would affect locations in Bavaria as a whole.

**Comment by chubin** [comment]
Maybe I miss something, but it looks like you have the same query several times. Anyway, it was a capaity issue, and even if worked for some locations (like `Munich`, but didn't work for `München` or `Minga`, it is still possible, because some of them being more popular could be cached, and so the data could be fetched from the cache; if the data would expire faster than the outage ends, the Munich query would not work either).

There are some (rare) cases where the data source outage is partial, and some server, responsible for some area is down (it should n't necessarily be the whole Bavaria; it may be some more random distribution, so that Munich would work and Ingolstadt won't), in this case it would also look like this, but as I said, this condition s very rare, and the first issue happens much more often (95% of the outages).

**Comment by chubin** [comment]
I close this one; please comment if it should be reopen
