### ISSUE TITLE
Correctly spelled location

### ISSUE THREAD

**Issue by rolfn** [chubin/wttr.in#503]
If I call
```
curl wttr.in/berlin
```
I get
```
Weather report: berlin
...
```
I suspect that the correct spelling of the location is known when the weather data is obtained (»Berlin« not »berlin«). Can you change the output in this way?

**Comment by chubin** [comment]
Actually, it is intentional behavior: if you are using `berlin` as the location name, the service assumes that you want to have it this way (the problem is more complex as it may seem, because wttr.in is multilingual tool, covering absolutely all locations in the world). Canonical name of the location in the official language of the place where it belongs is displayed under the forecast table.

**Comment by rolfn** [comment]
I understand. Many thanks.
