### ISSUE TITLE
weather-units bug

### ISSUE THREAD

**Issue by xgqfrms** [chubin/wttr.in#553]
# weather-units bug

https://github.com/chubin/wttr.in#weather-units

```sh
$  curl wttr.in/Shanghai?u

$  curl wttr.in/Shanghai?m

```

![image](https://user-images.githubusercontent.com/7291672/101321569-860f3b00-38a0-11eb-959f-8c5aca008d1f.png)

![image](https://user-images.githubusercontent.com/7291672/101321604-958e8400-38a0-11eb-9d1d-831d78f61d8b.png)

## but the default is OK

```sh
$  curl wttr.in/Shanghai

```

![image](https://user-images.githubusercontent.com/7291672/101321706-bce55100-38a0-11eb-9981-dcaf0500d425.png)

**Comment by suruaku** [comment]
You have to use quotes `"wttr.in/Shanghai?u"`

**Comment by chubin** [comment]
The problem here, exactly as @suruaku says, is not the service (or that it handles URL wrongly), but zsh. zsh tries to process the glob (it thinks that it is a glob because of the `?` in the name),
and it can't find any file matching this glob (`wttr.in/Paris?n`). If you run `setopt +o nomatch` first, it will work without any escaping

```
b1% curl wttr.in/?N
zsh: no matches found: wttr.in/?N
b1% setopt +o nomatch
b1% curl wttr.in/?N  
Weather report: Regensburg, Germany

    \  /       Partly cloudy
  _ /"".-.     16 °C          
    \_(   ).   ↑ 6 km/h       
    /(___(__)  10 km          
               0.0 mm      
...
```

**Comment by xgqfrms** [comment]
Thanks a lot!
