### ISSUE TITLE
How use wttr.in with aria2c?

### ISSUE THREAD

**Issue by LinArcX** [chubin/wttr.in#592]

**Comment by chubin** [comment]
Because of https://github.com/aria2/aria2/issues/190, it is not possible to use aria2c directly,
but you can easily do it with a small shell wrapper:

```
a2o() {
  TMP=$(mktemp /tmp/aria2c-XXXXXXXXXXXXXXX)
  IFS=+ aria2c --dir / -o "${TMP}" --allow-overwrite "$*" >& /dev/null &&
  cat "$TMP"
  rm "$TMP"
}
```

and then:

`$ a2o https://wttr.in?A`

Keep in mind, that:

1. With aria2c, you need explicitly specify the protocol (`http://` or `https://`),
2. To force ANSI output, you need to use the `?A` option.
