### ISSUE TITLE
For autodetected (based on IP) locations, country information seems to be ignored

### ISSUE THREAD

**Issue by chubin** [chubin/wttr.in#63]
Examples:

(from issue #62):

> when we do not pass any input to the url and it recognizes the location through ip address, the results are still from Carlisle, UK.

There are some other issues like that.

**Comment by KM4YRI** [comment]
I'm in Melbourne Florida.  wttr.in auto-locates to 'Melbourne', which pulls up Melbourne, Australia.

If I manually type in wttr.in/Florida, it pulls up [Florida, Cuba](https://en.wikipedia.org/wiki/Florida,_Cuba), literally a city in Cuba.

**Comment by wZguy** [comment]
Try `wttr.in/Melbourne,Florida` .

**Comment by chubin** [comment]
Another occurance: https://twitter.com/Matt24Ray/status/827517408311181312

**Comment by chubin** [comment]
@KM4YRI @wZguy @lfaraone Please check if it is better now. It should work now

**Comment by chubin** [comment]
MattRay has reported that it works for him now: 
https://twitter.com/Matt24Ray/status/827517408311181312

**Comment by KM4YRI** [comment]
> @KM4YRI @wZguy @lfaraone Please check if it is better now. It should work now

```wttr.in/Melbourne,Florida``` works, as does ```Try wttr.in/32901```, but ```Try wttr.in/Florida``` still brings up Florida, Cuba.  Ideally in ambiguous cases like this, the 'biggest' of the two by population or something to that effect should be used.  But at this point it's usable, if I just use my zip code.  So I'm content.

**Comment by chubin** [comment]
@KM4YRI It's actually already so like you say, but it does not work this way with Florida, because Florida,US is not a city/location, is a state, and states/countires are not supposed to be used here. So you can't check the weather in France or in Germany. I mean wttr.in/France or wttr.in/Germany will not work (though it would be a really good feature I think).

My original question was about autolocation: so what happens if you do curl wttr.in, do you still the the weather report for Melbourne,Australia or it is Mebourne,US now?

**Comment by cstok** [comment]
Another example, using the IP address for [dotgov.gov](https://dotgov.gov). The state is ignored and weather for a generic Reston, in this case Florida, is used. 

![image](https://user-images.githubusercontent.com/40079934/41203384-e7e24820-6ca3-11e8-8a84-7f0d4acfdfee.png)

![image](https://user-images.githubusercontent.com/40079934/41203358-aed5453c-6ca3-11e8-8610-93c31998f980.png)

![image](https://user-images.githubusercontent.com/40079934/41203360-b927b0b0-6ca3-11e8-9edc-54602720f1ae.png)

![image](https://user-images.githubusercontent.com/40079934/41203362-bcb336dc-6ca3-11e8-8365-5c28bddd628b.png)

**Comment by chubin** [comment]
@KM4YRI @wZguy @lfaraone @cstok

I've fixed several bugs related to geolocation based on IP-address.
```
curl wttr.in/@dotgov.gov
```
should now work as it should.

For other locations, if they are resolved incorrectly, use advanced location search using ~ in front of the location name:

~Florida
~Reston,Florida
etc.

In future, we should probably use advanced location search by default,
so the ~ will be not necessary.

Please check, if IP-based geolocation works for you now.

**Comment by wZguy** [comment]
I apologize for not responding here, for some reason I've completely failed to see the notifications here on github.
No, IP-based geolocation is still wildy incorrect, and when I use wttr.in I make sure to invoke it as `wttr.in/<city>,<State>` i.e., `curl wttr.in/Dallas,Tx`.
To be exact, I live in a city called Clinton. There are 23 states with a city called `Clinton`. [https://www.geodatos.net/en/homonymous-cities/clinton](url)
When I invoke it by default, I get a response that doesn't match any `Clinton` in the United States despite saying so. I know because I ran wttr.in against every state manually to double check, but I don't want to flood this comment with too many screenshots.
![image](https://user-images.githubusercontent.com/3733560/53382227-29e05e80-3939-11e9-95eb-1077e381c02e.png)
When I request specifically Clinton, I get:
![image](https://user-images.githubusercontent.com/3733560/53381878-da4d6300-3937-11e9-922f-1013043cce8d.png)
This is the same as asking for Clinton,Maryland:
![image](https://user-images.githubusercontent.com/3733560/53381836-ba1da400-3937-11e9-8b49-2ecde61133f8.png)
If I ask for Clinton,US I again get the results for Clinton,Maryland
![image](https://user-images.githubusercontent.com/3733560/53381927-0d8ff200-3938-11e9-93a6-897bf0deaa59.png)
If I request Clinton,UnitedStates, I receive the same response as Clinton,NorthCarolina:
![image](https://user-images.githubusercontent.com/3733560/53382386-b7bc4980-3939-11e9-8876-2156706cd7f9.png)
![image](https://user-images.githubusercontent.com/3733560/53382079-9ad34680-3938-11e9-9ae9-70153142acea.png)

I don't live in Clinton,Maryland or Clinton,North Carolina, and when I browse to any generic 'find your location from your IP' website, the results from those services are accurate. When viewing [http://wttr.in](url), I am also presented with the same result as `curl wttr.in` from my shell.
