### ISSUE TITLE
HTTPS redirect

### ISSUE THREAD

**Issue by xnekv03** [chubin/wttr.in#648]
Can you please make https redirect from http://wttr.in to https://wttr.in automatically?

Thanks

**Comment by xnekv03** [comment]
@aliskinr - Opera, Firefox. Just enter http://wttr.in to URL bar and no redirection will take place. You'll you stay on unsecured page.

**Comment by trekkie1701c** [comment]
I'd assumed this was intentional.  I understand the need for secrecy, but as a need for wide-ranging compatibility for something that doesn't have sensitive data (Ie, this is this the weather, it's not banking data and you're not entering any personalized info into it) it is helpful to not automatically redirect, for applications that don't support SSL, and I do actually utilize that in some areas where adding an automatic HTTPS redirect would break compatibility (I am not in a position to add SSL support to those applications or swap to ones that do)

**Comment by xnekv03** [comment]
@trekkie1701c 
few points
- all browsers [support SSL](https://www.ssl.com/faqs/browser-support-ssl-certificate/) so there is no compatibility issue whatsoever
- there is no reason why not to use SSL regardless of data transferred
- All major browsers plan to [discourage ](https://www.digicert.com/blog/not-secure-warning-what-to-do)users from using non encrypted connections
- SSL certificates are [free ](https://letsencrypt.org)and automatically renewable
- SSL redirect is standard all over the web regardless of content

**Comment by chubin** [comment]
Keep in mind that the primary usecase of wttr.in is the terminal, and many users are get used to use `curl wttr.in` (and not `curl https://wttr.in`), so the autoredirecton should be enabled for the browser only.

**Comment by chubin** [comment]
I've added automatic redirection HTTP => HTTPS (browser only). Please test

**Comment by xnekv03** [comment]
works, thanks

**Comment by trekkie1701c** [comment]
As feared, this did in fact break the tools I was using as they now just retrieve a "This page has moved" message and don't support HTTPS (yes, yes, everything is supposed to support HTTPS, etc, etc, etc.  This is just the weather, I'm helping some people out for free and their software doesn't support it and can't be upgraded, so sue me.  Sorry, I'm frustrated, and this is very much not the first time I've found a useful source of web-based weather info that didn't require HTTPS and didn't require me to download additional software which I can't do on the system I'm doing this on).

Is it possible to add exceptions for a specific browser agent?  I can at least spoof the browser agent that it's requesting with, and I guess that it doesn't show up as a non-browser when requesting.  I've tried to have it say that it's Curl (which I know, supports HTTPS, but it also doesn't seem to get redirected) and that doesn't seem to change the outcome.

**Comment by chubin** [comment]
> Is it possible to add exceptions for a specific browser agent?

Wait, have you seen my last comment? Redirection is off for all non-browser clients.
Try to `curl wttr.in` and you will see. No redirection.

So if you have some specific user-agent that is not automatically detected
by wttr.in as a plain-text agent, just let me know its name, and I will add it.

**Comment by chubin** [comment]
> I've tried to have it say that it's `curl`

It should work actually. If you have a terminal, please just try to run `curl wttr.in` and you will see

**Comment by trekkie1701c** [comment]
I have, but it seems to not be working in that regard.

Originally it was spoofing a user agent of "Mozilla/5.0 (X11; Linux i686; rv:2.0.1) Gecko/20100101 Firefox/4.0.1"

However due to your earlier comment I had tried to set it to the user-agent Curl uses ("curl/7.68.0").  However both of these seem to redirect.

Using Curl directly, however, does not.

**Comment by chubin** [comment]
Could you please query some unique location with your client? I will check what user agent header it sets indeed, because I have the feeling that it may use some other user agent. Could you query for `wttr.in/d248a2c8-bea9-41fd-b674-f45b7790390a` ? This will produce 404 of course, but it does not matter, we will see what user-agent is used.

**Comment by trekkie1701c** [comment]
Done.

**Comment by chubin** [comment]
Your user agent:

`Mozilla/5.0 (X11; Linux i686; rv:2.0.1) Gecko/20100101 Firefox/4.0.1`

**Comment by trekkie1701c** [comment]
I have to facepalm a bit here.  I had two versions of my script loaded; a debug script and, lower down, a stable version I hadn't set.  I hadn't considered that the second version might overwrite the agent variable that I'd set but it seems that happened.

It is working with the agent properly set to Curl.  I'm sorry for the fuss and thank you for your time.

**Comment by chubin** [comment]
That's fine! I am very glad that it works for you know. I think it is a little bit cleaner indeed, that the browser version has auto-redirect to HTTPS, and we implemented it, and found a solution for the clients that need plain HTTP. By the way, we could add an option, that would switch the auto redirection off
