### ISSUE TITLE
Localisation for `BENGALI - বাংলা`  language

### ISSUE THREAD

**Issue by appledora** [chubin/wttr.in#659]
Hi @chubin 
 I want to add localisation for `BENGALI` language.
 I opened this issue on GitHub as guided [here](http://wttr.in/:translation).
 If it's fine with you can you please assign me this issue and tell me the procedures? 

---

Steps:

To do:

* [x] Translate messages into Bengali
* [x] Translate help file into Bengali
* [x] v2.wttr.in translation

**Comment by chubin** [comment]
You either add to `FULL_TRANSLATION` or `PARTIAL_TRANSLATION` but not to the both. I've fixed it for you.

I've merged your changes and deployed them already. Could you please take a look:

https://bn.wttr.in

Could you please also add your name to the translators list? (`share/translation.txt`)

**Comment by appledora** [comment]
I already checked right after I got the merge notification xDD Thanks!! wttr is a really beautiful thing <3 Thanks for letting me contribute here!!

**Comment by chubin** [comment]
Could you please also translate these files:

* https://github.com/chubin/wttr.in/blob/master/lib/translations_v2.py
* https://github.com/chubin/wttr.in/blob/master/share/we-lang/we-lang.go#L362
* https://github.com/chubin/wttr.in/blob/master/share/we-lang/we-lang.go#L433

It is not much, just a couple of words.

**Comment by appledora** [comment]
On it :D

**Comment by chubin** [comment]
I've merged and deployed it; thank you very much, Nazia. Please test it:

https://bn.wttr.in/

The formatting issue is still there; we will fix it yet; but the rest seems to be working like a charm.
I like how it looks like in Bengali, even with this formatting issue, it looks like some old weather forecast
written on a wall of an ancient building. A thrilling look!

**Comment by appledora** [comment]
It feels really amazing to see my translations up there!! I am now using wttr daily on my terminal, while bragging to friends xDD

**Comment by chubin** [comment]
What terminal do you use if I am allowed to ask? Is it `konsole`? Or something else?
And is the Bengali translation displayed correctly in your terminal?

That is how it looks like in `konsole`:

![Selection_204](https://user-images.githubusercontent.com/3875145/139850614-7d95dbeb-e432-4d72-a57e-eb64e35fa310.png)

The formatting must be fixed of course, but the text is displayed correctly, isn't it?

**Comment by appledora** [comment]
I use `Guake` on `pop OS`. This is how it looks on my terminal. My terminal in general can't show bengali , it breaks up the Diphthongs into graphemes. But it seems, your terminal is doing a far better job at that xD

![image](https://user-images.githubusercontent.com/27975232/139852187-adda628c-641e-4161-aec7-73990f7415d9.png)

**Comment by chubin** [comment]
Usually I don't use `konsole`; I know that Konsole is the only terminal that properly shows Devanagari, that's why I started it to make a screenshot for you. 

Guake is as far as I know gnome-terminal based i.e. it is VTE-based, and so it does not handle Devanagari properly.
You can try `konsole` (it needs a lot of dependencies though).

I find it is really pity, that such beautiful script as Devanagari is almost never displayed properly,
but it is very hard to implement it comparing with such scripts as Latin, Cyrillic or Greek
(that's why we still have this rendering problem on wttr.in, but we will fix them someday, I hope).

BTW, you still see the untranslated version, without your recent fixes, that is because you access
a cached report that was not updated still. Try to do `curl bn.wttr.in/Dhaka` for example.
(and the cached version will be outdated soon anyway)

**Comment by appledora** [comment]
Yep, it's working better now! I really appreciate your enthusiasm regarding Bengali. Hit me up, if I can help you with it in anyways !! 

![image](https://user-images.githubusercontent.com/27975232/139873768-5a5d1125-9f09-479f-8609-3d37e1791676.png)

**Comment by chubin** [comment]
I moved the rendering subtasks to #676, and so this issue is finished and can be closed now.
@appledora thanks a lot for your help!
