### ISSUE TITLE
Temperature readings differ when request language is not default/English

### ISSUE THREAD

**Issue by vanderlyle** [chubin/wttr.in#668]
I've come across this inconsistency that if I switch the request language I get different temperature readings in the response: 

![2021-10-28-190128_1280x800_scrot](https://user-images.githubusercontent.com/24830324/139301961-9b70769a-c339-49bc-a4d5-083f58331eb1.png)

I've run the above test a few times to rule out data being updated between the individual requests.
Is it possible that the data for the non-default or non-English languages is cached / less frequently updated or what else could cause this?

Thanks and keep up the good work!

**Comment by chubin** [comment]
Yes, all the data is cached. That's why it is not unlikely that you can get some differing results, if some of the responses (most probably it is English, as the default one) is already cached. Of course, 6 ⁰C difference is a little bit too much, but who knows. What you can also do in future, you can add something like `&nonce=$RANDOM` to the query, to bypass at least the first caching tier.

**Comment by chubin** [comment]
And yes, non-English answers must be more accurate/actual, of course; not other way around

**Comment by vanderlyle** [comment]
Thanks chubin, I tried your suggestion and haven't run into any huge disparities in the last few days so I'm closing the issue.
