### ISSUE TITLE
Deviating values when using format

### ISSUE THREAD

**Issue by siredmar** [chubin/wttr.in#740]
The output values diverge when use a format instead of the standard output.

```
$ curl "wttr.in/Berlin?format=3"
Berlin: ⛅️  +15°C

$ curl "wttr.in/Berlin?&format=%l:+%C+%c%t" 
Berlin: Partly cloudy ⛅️ +15°C

$ curl "wttr.in/Berlin"
Weather report: Berlin

     \  /       Partly cloudy
   _ /"".-.     +12(11) °C     
     \_(   ).   → 13 km/h      
     /(___(__)  10 km          
                0.0 mm         

<cut> ...

```

**Comment by chubin** [comment]
Yes, it is possible because of the caching issues. Because of the high load on the service, there data is cached by several caching layers (with different life-time), and I think that here it is exactly this problem.

```
~$ curl "wttr.in/Berlin?Q0&nonce=$RANDOM"
     \  /       Partly cloudy
   _ /"".-.     +23(25) °C
     \_(   ).   → 11 km/h
     /(___(__)  10 km
                0.1 mm
~$ curl "wttr.in/Berlin?Q0&nonce=$RANDOM&format=3"
Berlin: ⛅️  +23°C
```


I close this in favor of #705. If you would like to reopen this issue, please comment,
or better switch to #705
