### ISSUE TITLE
curl wttr.in not working

### ISSUE THREAD

**Issue by jrysa** [chubin/wttr.in#858]
It seems that wttr.in has some outage. It still loading but without response.
```
❯ curl wttr.in
curl: (52) Empty reply from serve
```

**Comment by agail** [comment]
@chubin problem with hosting service?

**Comment by wjohnhaynes** [comment]
My very reliable startup script did not work this morning. The problem is with a curl for the weather "curl wttr.in/"mycity".
Manually tried London, Chicago, New York. Nothing resolves. Tried ping and it could not resolve. I was able to curl google and ping the dns server. Just curl wttr.in seems to be down.

**Comment by wjohnhaynes** [comment]
I tried again just now and it seems to be back up, connected when I used curl -v

**Comment by jrysa** [comment]
Yeah now it seems that it is working again.
