### ISSUE TITLE
Empty reply

### ISSUE THREAD

**Issue by helby255** [chubin/wttr.in#904]
Hi. I checked it in 3 different ip and always have the same answer:
```
curl wttr.in/:help
curl: (52) Empty reply from server
```

**Comment by helby255** [comment]
Dup: https://github.com/chubin/wttr.in/issues/903

**Comment by sikhdev** [comment]
I would recommend you visit the URL in a web browser to see what the reason is before opening an issue. The reason I say that is because going to the URL will show you the exact reason they are offline. Usually when you are getting this message its because they are out of capacity and just need to wait for the next day for the limit to reset.

Right now on the page I am seeing

```
Sorry, we processed more than 1M requests today and we ran out of our datasource capacity.
We hope to solve the problem as soon as possible, so you can enjoy
your favourite weather service 24x365 even if it rains or snows.
```
