### ISSUE TITLE
readme.md does not show the weather right on live test

### ISSUE THREAD

**Issue by kmgrime** [chubin/wttr.in#926]
This is probably since its pointed at a .png? Maybe it would be better to have it as a link so when you click it, the actual service shows you your weather location.

**Comment by kmgrime** [comment]
There is aswell several broken image links in the readme that should either have been provided with a non-broken image source or refactored to independent examples.

**Comment by polygonnedpotato** [comment]
This is an issue* with GitHub, as it is showing you a cached version of the README.

* This is not really an issue or a bug, but rather a smart way to save resources, as it means that GitHub would only need to show you the latest cached version of the README, instead of constantly re-processing it over-and-over again. It also means that it won't send requests to wttr over and over again, preventing the service from prematurely running out of requests.
